import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F8F9FA',
    },
    header: {
        height: 56,
        backgroundColor: '#009246',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
    },
    backButton: {
        padding: 4,
    },
    backIcon: {
        color: '#FFFFFF',
        fontSize: 24,
        fontWeight: 'bold',
    },
    headerTitle: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '700',
    },
    backPlaceholder: {
        width: 24,
    },
    scrollContainer: {
        padding: 16,
        paddingBottom: 110,
    },
    slotCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        padding: 14,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
        borderWidth: 1,
        borderColor: '#EAECEE',
        elevation: 1,
    },
    slotCardError: {
        borderColor: '#D9383A',
        backgroundColor: '#FFF5F5',
    },
    slotDetails: {
        flex: 1,
        marginRight: 12,
    },
    slotName: {
        fontSize: 15,
        fontWeight: '600',
        color: '#2C3E50',
        marginBottom: 2,
    },
    asterisk: {
        color: '#D9383A',
        fontWeight: '700',
    },
    slotStatus: {
        fontSize: 12,
        color: '#95A5A6',
    },
    errorFieldMessage: {
        color: '#D9383A',
        fontSize: 11,
        fontWeight: '500',
        marginTop: 4,
    },
    uploadTriggerButton: {
        width: 48,
        height: 48,
        borderRadius: 8,
        backgroundColor: '#E8F5E9',
        justifyContent: 'center',
        alignItems: 'center',
    },
    thumbnailContainer: {
        position: 'relative',
    },
    thumbnailPreview: {
        width: 54,
        height: 54,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#BDC3C7',
    },
    removeBadge: {
        position: 'absolute',
        top: -8,
        right: -8,
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        elevation: 2,
    },
    sectionTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#34495E',
        marginTop: 8,
        marginBottom: 10,
    },
    horizontalScrollWrapper: {
        flexDirection: 'row',
        marginVertical: 4,
    },
    addOtherButtonCard: {
        width: 74,
        height: 74,
        borderRadius: 8,
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: '#BDC3C7',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
        backgroundColor: '#FFFFFF',
    },
    addOtherText: {
        fontSize: 10,
        color: '#7F8C8D',
        fontWeight: '600',
        marginTop: 4,
    },
    otherThumbnailWrapper: {
        position: 'relative',
        marginRight: 12,
    },
    otherThumbnail: {
        width: 74,
        height: 74,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#EAECEE',
    },
    otherRemoveBadge: {
        position: 'absolute',
        top: 2,
        right: 2,
        backgroundColor: 'rgba(217, 56, 58, 0.9)',
        borderRadius: 10,
        padding: 2,
    },
    bottomDock: {
        position: 'absolute',
        bottom: 0,
        width: '100%',
        backgroundColor: '#FFFFFF',
        padding: 16,
        borderTopWidth: 1,
        borderColor: '#EAECEE',
    },
    submitButton: {
        backgroundColor: '#009246',
        height: 48,
        borderRadius: 8,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 2,
    },
    submitButtonText: {
        color: '#FFFFFF',
        fontSize: 15,
        fontWeight: '700',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.4)',
        justifyContent: 'flex-end',
    },
    bottomSheetContainer: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 16,
        borderTopRightRadius: 16,
        padding: 24,
        paddingBottom: 36,
    },
    sheetTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#2C3E50',
        textAlign: 'center',
        marginBottom: 20,
    },
    sheetRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    sheetActionItem: {
        alignItems: 'center',
    },
    iconCircle: {
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 8,
        elevation: 1,
    },
    sheetActionText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#34495E',
    },
    lightboxOverlay: {
        flex: 1,
        backgroundColor: '#000000',
        justifyContent: 'center',
        alignItems: 'center',
    },
    lightboxCloseButton: {
        position: 'absolute',
        top: 40,
        right: 20,
        zIndex: 10,
        padding: 8,
    },
    fullScreenImage: {
        width: width,
        height: '84%',
    },
});