import { StyleSheet, Dimensions } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F4F6F8',
    },
    header: {
        height: 56,
        backgroundColor: '#009246',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 8,
    },
    backButton: {
        width: 40,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
    },
    backIcon: {
        fontSize: 24,
        color: '#FFF',
        fontWeight: 'bold',
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#FFF',
    },
    backButtonPlaceholder: {
        width: 40,
    },
    scrollContent: {
        paddingHorizontal: 16,
        paddingTop: 16,
        paddingBottom: 40,
    },
    overviewCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingVertical: 20,
        paddingHorizontal: 16,
        alignItems: 'center',
        marginBottom: 14,
        borderWidth: 1,
        borderColor: '#EAEAEA',
    },
    iconContainer: {
        padding: 10,
        borderRadius: 50,
        marginBottom: 10,
    },
    amountContainer: {
        flexDirection: 'row',
        alignItems: 'baseline',
        marginBottom: 8,
    },
    pesoSign: {
        fontSize: 18,
        fontWeight: '700',
        color: '#2C3E50',
        marginRight: 2,
    },
    amountValue: {
        fontSize: 26,
        fontWeight: '800',
        color: '#2C3E50',
    },
    statusBadge: {
        paddingHorizontal: 12,
        paddingVertical: 4,
        borderRadius: 20,
        marginBottom: 8,
    },
    statusText: {
        fontSize: 12,
        fontWeight: '700',
    },
    dateTimeText: {
        fontSize: 12,
        color: '#7F8C8D',
    },
    detailsCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 14,
        borderWidth: 1,
        borderColor: '#EAEAEA',
    },
    cardSectionTitle: {
        fontSize: 15,
        fontWeight: '700',
        color: '#2C3E50',
        marginBottom: 14,
        borderBottomWidth: 1,
        borderBottomColor: '#F4F6F8',
        paddingBottom: 6,
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#F9FAFB',
    },
    rowLabel: {
        fontSize: 13,
        color: '#7F8C8D',
    },
    rowValue: {
        fontSize: 13,
        fontWeight: '500',
        color: '#34495E',
        textAlign: 'right',
    },
    attachmentRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        backgroundColor: '#F8F9FA',
        padding: 12,
        borderRadius: 8,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: '#EAEAEA',
    },
    attachmentLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 0.8,
    },
    attachmentName: {
        fontSize: 13,
        color: '#34495E',
        marginLeft: 8,
    },
    attachmentRight: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    viewText: {
        fontSize: 12,
        color: '#009246',
        fontWeight: '600',
        marginRight: 2,
    },
    helpButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        marginTop: 10,
    },
    helpButtonText: {
        fontSize: 14,
        color: '#009246',
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'flex-end',
    },
    bottomSheetContainer: {
        backgroundColor: '#FFFFFF',
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 30,
    },
    notchIndicator: {
        width: 40,
        height: 4,
        backgroundColor: '#BDC3C7',
        borderRadius: 2,
        alignSelf: 'center',
        marginBottom: 16,
    },
    sheetTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#2C3E50',
        marginBottom: 16,
    },
    radioRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
    },
    radioCircle: {
        width: 20,
        height: 20,
        borderRadius: 10,
        borderWidth: 2,
        borderColor: '#BDC3C7',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
    },
    radioCircleSelected: {
        borderColor: '#009246',
    },
    radioInnerDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: '#009246',
    },
    radioLabelText: {
        fontSize: 14,
        color: '#34495E',
    },
    inputLabel: {
        fontSize: 14,
        fontWeight: '600',
        color: '#2C3E50',
        marginTop: 16,
        marginBottom: 8,
    },
    textArea: {
        backgroundColor: '#F8F9FA',
        borderWidth: 1,
        borderColor: '#EAEAEA',
        borderRadius: 8,
        padding: 12,
        fontSize: 13,
        color: '#2C3E50',
        textAlignVertical: 'top',
        height: 80,
    },
    sheetButtonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
    },
    sheetButton: {
        flex: 1,
        height: 44,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sheetButtonCancel: {
        backgroundColor: '#F4F6F8',
        marginRight: 10,
        borderWidth: 1,
        borderColor: '#EAEAEA',
    },
    sheetButtonSend: {
        backgroundColor: '#009246',
    },
    cancelBtnText: {
        color: '#7F8C8D',
        fontWeight: '600',
    },
    sendBtnText: {
        color: '#FFFFFF',
        fontWeight: '600',
    },
    successModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    successBox: {
        width: Dimensions.get('window').width * 0.8,
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 24,
        alignItems: 'center',
    },
    successTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#2C3E50',
        marginTop: 14,
        marginBottom: 8,
    },
    successDescription: {
        fontSize: 13,
        color: '#7F8C8D',
        textAlign: 'center',
        lineHeight: 18,
        marginBottom: 20,
    },
    successCloseBtn: {
        backgroundColor: '#009246',
        paddingHorizontal: 30,
        paddingVertical: 10,
        borderRadius: 8,
    },
    successCloseText: {
        color: '#FFFFFF',
        fontWeight: '600',
        fontSize: 14,
    },
});